"""add_lecture_and_weekly_schedule_tables

Revision ID: 282029d1d9cb
Revises: 88de22c8be10
Create Date: 2025-12-14 13:17:53.874757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282029d1d9cb'
down_revision = '88de22c8be10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecture_name_ar', sa.String(length=200), nullable=False),
    sa.Column('lecture_name_en', sa.String(length=200), nullable=False),
    sa.Column('circle_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('shown_on_website', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lectures_id'), 'lectures', ['id'], unique=False)
    op.create_table('weekly_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_schedules_id'), 'weekly_schedules', ['id'], unique=False)
    op.create_table('lecture_teachers',
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lecture_id', 'teacher_id')
    )
    op.add_column('session_participations', sa.Column('lecture_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_session_participations_lecture_id'), 'session_participations', ['lecture_id'], unique=False)
    op.create_foreign_key(None, 'session_participations', 'lectures', ['lecture_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_participations', type_='foreignkey')
    op.drop_index(op.f('ix_session_participations_lecture_id'), table_name='session_participations')
    op.drop_column('session_participations', 'lecture_id')
    op.drop_table('lecture_teachers')
    op.drop_index(op.f('ix_weekly_schedules_id'), table_name='weekly_schedules')
    op.drop_table('weekly_schedules')
    op.drop_index(op.f('ix_lectures_id'), table_name='lectures')
    op.drop_table('lectures')
    # ### end Alembic commands ###
