"""add_student_details

Revision ID: fbec4d3b411b
Revises: 3ba7aaddeb76
Create Date: 2025-12-13 14:59:38.913199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbec4d3b411b'
down_revision = '3ba7aaddeb76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('from_surah', sa.String(length=50), nullable=False),
    sa.Column('to_surah', sa.String(length=50), nullable=False),
    sa.Column('from_verse', sa.Integer(), nullable=False),
    sa.Column('to_verse', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.add_column('students', sa.Column('sex', sa.String(length=10), nullable=True))
    op.add_column('students', sa.Column('date_of_birth', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('place_of_birth', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('home_address', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('nationality', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('academic_level', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('grade', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('school_name', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('guardian_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'guardian_id')
    op.drop_column('students', 'school_name')
    op.drop_column('students', 'grade')
    op.drop_column('students', 'academic_level')
    op.drop_column('students', 'nationality')
    op.drop_column('students', 'home_address')
    op.drop_column('students', 'place_of_birth')
    op.drop_column('students', 'date_of_birth')
    op.drop_column('students', 'sex')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
